### ISSUE TITLE
dhcp issue with 0.2-15 ?

### ISSUE THREAD

**Issue by Azenet** [ovh/overthebox-feeds#10]
Hi,

Somehow the OTB FS got corrupted so I had to flash it, I used the latest image from 2 days ago at `http://downloads.overthebox.ovh/trunk/x86/64/openwrt-x86-64-embedded-ext4.img.gz`, which installed 0.2-15 according to the overview page. Since then, there is an issue with odhcpd : whenever a change is made to any interface, I have to uncheck "Disable DHCP on this interface" everytime on eth0, otherwise the OTB will not reply to any DHCP request from the LAN network. There are several repeated entries for DHCP on the eth0 "General setup" page. This wasn't happening before flashing.

**Comment by sduponch** [comment]
Linked with: https://github.com/ovh/overthebox-feeds/pull/45
