### ISSUE TITLE
VOIP - QOS issues

### ISSUE THREAD

**Issue by MetallianFR68** [ovh/overthebox-feeds#1063]
I have OTB for aggregating 4G + ADSL
On previous versions of overthebox, I managed to make the VOIP work perfectly.
I juste created a QOS CLASS telling to use ONLY ADSL
It was the only way to make VOIP work flawlessly

Since the 0.6-24 auto update, everything is broken again.
The DSCP menu doesn't allow me to "edit" or "add" a class.
I can only add rules with predefined classes
How can I edit my own class ?
How can I tell VOIP to exclusively use the ADSL connection

I understand this is not what the OTB is for.
OTB is flawless for web/mail etc ... but I can't get the VOIP work otherwise.
We are a lawfirm with 7 VOIP phone and we need to find a solution quickly

Thanks for your answers

Best regards

**Comment by gregdel** [comment]
Hi,
If you want to route non TCP traffic through an interface, you can add a rule to your network config.
Let's say you want to route everything going to **1.1.1.1** via **wan1**.

First of all you need to get the table used for **wan1**, you can use this command:
```
root@OverTheBox:~# uci get network.wan1.ip4table
201
```

Then you have to add a rule to your network config (`/etc/config/network`):
```
config rule
        option dest   '1.1.1.1/32'
        option lookup '201'
```

Once this rule is added, all your traffic towards **1.1.1.1** will go through **wan1**.
