### ISSUE TITLE
Public IP not updated when changing on mainpage

### ISSUE THREAD

**Issue by naxnaxnax** [ovh/overthebox-feeds#126]
On the home page, the boxes of your interfaces display the public IP of each interface. If the public IP change without disconnecting the interface (like when ADSL lines resets), the public IP isn't updated. Even though the MPTCP tunnel is reset.

**Comment by sduponch** [comment]
Hi, it is a know issue (not yet implemented). I will work on it very soon, thanks for your report.

**Comment by sduponch** [comment]
Link with #129

**Comment by sduponch** [comment]
Fixed in 0.5.0 and later
