### ISSUE TITLE
erreur à la compilation

### ISSUE THREAD

**Issue by clembert** [ovh/overthebox-feeds#148]
Bonjour,

Après avoir suivi les indications du paragraphe "Compile from source" pour installer le service overthebox sur un hôte ubuntu x86, et après avoir préparer les requis et lancer la compilation, j'obtiens ces messages d'erreur : 

./overthebox-openwrt/include/toplevel.mk:65: recipe for target 'prepare-tmpinfo' failed
make[1]: *** [prepare-tmpinfo] Error 25
./overthebox-openwrt/include/toplevel.mk:177 : la recette pour la cible « world » a échouée
make: *** [world] Erreur 2

Pouvez-vous m'aider ?

**Comment by MartinWetterwald** [comment]
Bonjour,

Il manque des informations. L'erreur proprement dite n'apparaît pas dans le copier/coller.
Pouvez-vous copier/coller les erreurs après avoir lancé la compilation avec un seul thread et en mode verbose ? (-j 1 V=s)

**Comment by clembert** [comment]
Bonjour,

Voici le résultats : 

Duplicate feed name 'overthebox', line: 7
Duplicate feed name 'overthebox', line: 7
Duplicate feed name 'overthebox', line: 7
./overthebox-openwrt/include/toplevel.mk:65: recipe for target 'prepare-tmpinfo' failed
make[1]: *** [prepare-tmpinfo] Error 25
./overthebox-openwrt/include/toplevel.mk:177 : la recette pour la cible « world » a échouée
make: *** [world] Erreur 2

**Comment by debiansid** [comment]
check your feeds.conf, youhave duplicate feed name, just keep one.
