### ISSUE TITLE
What is function of this domain

### ISSUE THREAD

**Issue by debiansid** [ovh/overthebox-feeds#220]
provisionning.overthebox.net

**Comment by MartinWetterwald** [comment]
This is a daemon that tells the OverTheBox what to do. The OverTheBox contact it periodically and asks what it should do.

Unfortunately we can't give you more details about the internals on OVH side.

**Comment by debiansid** [comment]
I am wondering if you can provide the service to other cable company with your architecture services.

**Comment by debiansid** [comment]
Such as I run tun and socks services on my own VPS and with my FTTB connection.

**Comment by gregdel** [comment]
What do you mean ? You don't need this domain if you run your own infrastructure :)

**Comment by debiansid** [comment]
Currently my local otb continues to connect this domain, and I can not run glorytun-Udp on it. Real time graph shows nothing. My idea is running  shadowsocks-libev for tcp and glorytun-udp for udp traffic. Would you please help me on that? Thank you Sir
