### ISSUE TITLE
Realtime traffic graph does not show up

### ISSUE THREAD

**Issue by debiansid** [ovh/overthebox-feeds#229]
There is no data showing on realtime traffic. I have no idea how to make it work. My modem is in bridge mode.

**Comment by stefb69** [comment]
Yes I have the same issue. I use a configuration with each box on a separate vlan, on different network subnets and (2 freebox and 1 4G modem). Hardware is a pcengine apu 2.

**Comment by gregdel** [comment]
Hey guys, sorry for the late reply. Do you still have the issue with the current stable version (0.5.3) ?

**Comment by gregdel** [comment]
We're now in 0.6.10, we'll reopen an issue if the problem persist in this version
