### ISSUE TITLE
Installation sous hyper-v

### ISSUE THREAD

**Issue by ftoyon** [ovh/overthebox-feeds#3]
Bonjour,

Est il possible d'installer OverTheBox dans une VM hyper-v ?

**Comment by liberodark** [comment]
Oui mais pas pratique dans l'utilisation

**Comment by ftoyon** [comment]
Bonjour,

J'ai essayé de l'installer à partir de l'image ou par compilation mais aucune des 2 options ne démarre !

P.S.: Je n'ai pas compris pourquoi ce ne serrai pas pratique dans l'utilisation ?

**Comment by djam-hawaii** [comment]
Bonjour @liberodark ,

Je relance la question de @ftoyon. Je suis dans le même cas:
- comment fait-on l'installation?
- Pq ce n'est pas pratique?

merci!

**Comment by liberodark** [comment]
Ben plus plusieurs raisons mais cela est possible !
Il vous suffit de tester si cela ne pose pas de problème à la longue
