### ISSUE TITLE
iptraf should be replaced by iptraf-ng

### ISSUE THREAD

**Issue by zoobab** [ovh/overthebox-feeds#46]
The old Iptraf has a bug with tun0 interfaces (it simply crashes), and it should be replaced by iptraf-ng, which is maintained.

**Comment by sduponch** [comment]
Looking at it :)

**Comment by zoobab** [comment]
Read this:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=499756

"It's a bug in the upstream version of iptraf - too bad this tool is abandoned now."

**Comment by sduponch** [comment]
Makefile done, should be in next release.

**Comment by zoobab** [comment]
Otherwise it was here: https://github.com/openwrt/packages/tree/master/net/iptraf-ng

**Comment by sduponch** [comment]
Link with https://github.com/ovh/overthebox-feeds/pull/47

**Comment by sduponch** [comment]
Merged, Thank you for help
