### ISSUE TITLE
mismatch between interface and device in mwan3otb

### ISSUE THREAD

**Issue by jlabrous** [ovh/overthebox-feeds#5]
When I create a port using Wifi scan for tethering,
I get by default a new symbolic interface  "wwan" linked to "wlan0" real ethernet device
Tracking is launch like this:
lua /usr/sbin/mwan3track -i wwan -d wlan0 ...
but it tries to operate with symbolic interface instead of the device itself.
So link never commes UP.

If I force symbolic name to wlan0 be equal to device name, everything is ok

**Comment by sduponch** [comment]
Checking...

**Comment by sduponch** [comment]
Linled with https://github.com/ovh/overthebox-feeds/pull/68

**Comment by angt** [comment]
Fixed in #378 #380 #381 (and counting... ^^)
