### ISSUE TITLE
Add something like ntop in the web interface

### ISSUE THREAD

**Issue by gregdel** [ovh/overthebox-feeds#560]
Someone told me he wants to see who's doing traffic and on which remote IP, something like ntop but in the browser

**Comment by PouuleT** [comment]
This page https://ip-of-your-otb/cgi-bin/luci//admin/status/realtime/connections/  is providing a graph of the number of connections plus a list of all the current connections (with IP source / port source / IP destination / port destination / Quantity of data transmitted )
