### ISSUE TITLE
bande passante supportée

### ISSUE THREAD

**Issue by xilox75** [ovh/overthebox-feeds#6]
Bonjour,

J'ai une connexion par la fibre avec un débit de 800/40  

J'aurai souhaiter savoir si la limitation de la bande passante est lié au matériel ou es ce possible de construire son propre routeur pour atteindre des pics au delà des 600 Mb
Es ce lié aux limitations du cryptage du processeur ?

Merci d'avance pour vos retours.

Vincent

**Comment by sduponch** [comment]
Bonjour,

Les deux, la limitation est principalement CPU (~130Mbits avec le Nuc OTB) et coté infrastructure 250Mbits (évolutifs). Mais nous visons principalement le marché 4*25 Mbits...

Cordialement,
DUPONCHEEL Sébastien
