### ISSUE TITLE
Feature : TTL overriding

### ISSUE THREAD

**Issue by epalzeolithe** [ovh/overthebox-feeds#632]
Hi,

it's possible to override the TTL of  each packets when going through the gateway, to a default TTL ?

Thanks in advance :)

**Comment by gregdel** [comment]
Hi, you can do this with the `iptables` command.
You should do it in the mangle table / postrouting chain.
e.g.
```
iptables -t mangle -I POSTROUTING -d 8.8.8.8 -p tcp -j TTL --ttl-set 1
```

However, according to the man (iptables-extensions):
> Setting or incrementing the TTL field can potentially be very dangerous, so it should be avoided at any cost.

You can add custom rules in the web interface under firewall > custom rules.

**Comment by gregdel** [comment]
Any news ? Did you try the solution I gave you ?

**Comment by epalzeolithe** [comment]
Hello, not yet, i had to fully reinstall my OTB, and changed the whole topology of my LAN,

i will :)

**Comment by epalzeolithe** [comment]
Hello

i did it on my otb

the command iptables, is it persistent or do i need to run it at each start ?
