### ISSUE TITLE
shadowsocks: invalid number of cpu detected in the raspberry pi 3

### ISSUE THREAD

**Issue by gregdel** [ovh/overthebox-feeds#649]
This command works:
```
 echo $((`cat /sys/devices/system/cpu/present | sed 's/0-//'` + 1))
```

**Comment by debiansid** [comment]
How can you run it on raspberry pi3?

**Comment by angt** [comment]
@debiansid coming soon :)

**Comment by debiansid** [comment]
@angt I am still looking forward to activate it from China, coz there is no service plan from OVH for China

**Comment by gregdel** [comment]
@debiansid https://twitter.com/EssaBash/status/900690888623566849
