### ISSUE TITLE
otbv2: Switch port disappears 

### ISSUE THREAD

**Issue by gregdel** [ovh/overthebox-feeds#793]
I changed the port 10's port configuration:
![](https://user-images.githubusercontent.com/1162110/31601613-bea06d42-b25a-11e7-847c-687b19526fd0.png)

And the port disappeared from the simple switch interface:
![yo](https://user-images.githubusercontent.com/1162110/31601640-d823da6a-b25a-11e7-9c2e-9eeb017f1b81.png)

![](https://w000t.me/5d71136b36)

**Comment by PouuleT** [comment]
By design, the UI skip tagged ports as it would show the management port 15
```
config switch_vlan
	option device 'otbv2sw'
	option vlan '2'
	option ports '1 2 4 5 6 7 8 9 10t 11 12 13 14 15t 18'
```
How should we handle this ? Display tagged ports in a different color and manually skip the management port ?
