### ISSUE TITLE
TTL persistent

### ISSUE THREAD

**Issue by epalzeolithe** [ovh/overthebox-feeds#863]
Hello

I need to change on the fly the TTL on each outgoing packet through each WAN (not the packets going through the tunnel)

Is il the right command for the WANs ?

iptables -t mangle -I POSTROUTING -d 8.8.8.8 -p tcp -j TTL --ttl-set 65

And is it persistent after reboot?

**Comment by gregdel** [comment]
iptables is not persistent, you can add the rules manually in `/etc/firewall.user` or via the web interface "Firewall > Custom Rules". If your custom rules are in this file, they will get applied on the next reboot.

What's your use case for changing the TTL ?

**Comment by epalzeolithe** [comment]
tethering cloaking

**Comment by epalzeolithe** [comment]
Well, iptables change seems to be persistent

i use this command instead for each VLAN

iptables -t mangle -A PREROUTING -i eth0.3 -j TTL --ttl-set 65

**Comment by gregdel** [comment]
Does this iptables command fixes your "issue" ? :)

**Comment by epalzeolithe** [comment]
Thanks !
