### ISSUE TITLE
No tunnel after restoring a configuration

### ISSUE THREAD

**Issue by epalzeolithe** [ovh/overthebox-feeds#864]
Most of the time, when i restore a config in System/Backup menu,

the link aggregation is broken. The OTB acts as just as a bridge using only one gateway (probably the metric 1 gateway).

I tried several time to re-register the service (register menu). But it says that the device is already register.

Of course, i've got the same situation after a reboot.

The only way is to reset to factory settings, then register the device properly, then it works.

It's terribly annoying because you cannot use the backup configuration.

Do you where it comes from ?

**Comment by gregdel** [comment]
How do you backup your configuration ? Using the web interface ?

One command that could be useful for you is `otb-action-configure` it tells the device to fetch its configuration.

**Comment by epalzeolithe** [comment]
Thank you !
