### ISSUE TITLE
Disable DNS servers of interfaces which are down

### ISSUE THREAD

**Issue by rhertzog** [ovh/overthebox-feeds#909]
I have two ADSL connection one over Free/Proxad and one over OVH. When my Free/Proxad connection goes down for an extended time, the DNS server integrated in the Freebox will start to respond to all queries with an IP leading back to the Freebox (this is made so that users get to see a nice page explaining that their internet access is down instead of just nothing happening). And it returns the public IP of the Freebox.

Unfortunately /tmp/resolv.conf.auto has the Freebox IP first so all DNS queries on the network will get answers leading users back to the public IP of the Freebox which will be routed over overthebox's VPN via the still-working OVH connection and obviously we are never able to connect to anything...

I don't know of any option to disable this annoying feature of the Freebox (although I requested it here: https://dev.freebox.fr/bugs/task/22525) so overthebox should be smart enough to disable the DNS server associated to an interface which is down.

In the mean time I stopped using the DNS server of the freebox for the Freebox interface and I have put Google's public DNS server instead. But I don't like this.

**Comment by PouuleT** [comment]
Thanks for the feedback!

There's already an opened issue for this matter #851
